[1.x] Add support for "page names"
laravel/folio pull request #54
Opened 2023-07-27 16:57 UTC by ryangjchandler

**Still a work-in-progress - leaving in draft until I can finish later today.**

There's currently no way to generate the URL to a Folio page by name, similar to how `route('foo')` works. This pull request aims to introduce that functionality.

The `Folio::route()` method inside of your `FolioServiceProvider` now has an additional parameter `$names`. This is an array of key-value pairs where the key is the pretty-name for the page and the value is the path to the Blade file.

```php
Folio::route(
    path: resource_path('views/pages'),
    names: [
        'users.index' => 'users/index.blade.php',
        'users.show' => 'user/[User].blade.php',
    ]
);
```

By registering these names, it's then possible to use the `Laravel\Folio\url()` function to generate URLs in a similar fashion to `route().`

```blade
<a href="{{ Laravel\Folio\url('users.index') }}">
    Users
</a>

<a href="{{ Laravel\Folio\url('users.show', $user) }}">
    John Doe
</a>

<a href="{{ Laravel\Folio\url('users.show', ['User' => $user]) }}">
    John Doe
</a>
```

TODO:
* [ ] Support bindings, i.e. `Post:slug` (`UrlRoutable && $parameter->{$binding}`)
* [ ] Handle `UrlRoutable` values inside of `$parameters`
* [ ] Handle `BackedEnum` inside of `$parameters`

2023-07-31 08:46 UTC, nunomaduro requested changes
Can you address my feedback, and rebase this to see if tests are passing against Windows?

2023-07-31 08:46 UTC, nunomaduro commented on src/Exceptions/UrlGenerationException.php
> +    public static function forMissingParameter(string $path, string $parameter): static
Can you add a simple comment to this method, like we do in any other methods in this project?

2023-07-31 08:46 UTC, nunomaduro commented on src/FolioManager.php
> +    public function __construct(
Can you add a simple comment to this method, like we do in any other methods in this project?

2023-07-31 09:34 UTC, ryangjchandler commented on src/UrlGenerator.php
> +                    throw UrlGenerationException::forMissingParameter($uri, $name);
Simple test added.

2023-08-04 10:36 UTC, mokhosh commented
Great work here.
If I may have a suggestion, I would say the beauty of Folio is the fact that you can get away with zero configuration for the routing part.
Is it possible to come up with a nice convention in addition to these explicit methods, so we can just do what we would normally do in folio and have named routes or named Folios as well?

2023-08-09 16:48 UTC, nunomaduro commented
Continuing this work here: https://github.com/laravel/folio/pull/79.

2023-08-09 16:48 UTC, closed without merging